//
//  ParityArtifact.swift
//  AudioToolTestSupport
//
//  Reading the reference outputs recorded by Parity/generate.py.
//

import Foundation

/// A recorded run of a reference implementation.
///
/// Generated by `Parity/generate.py` from the MLX Python under `Models/python/`,
/// which is what every Swift model here was ported from. See `Parity/README.md`.
///
/// The artifact carries the **input tensor**, not a path to a wav: decoding the
/// same file through soundfile and through AVFoundation can differ in the last
/// bit or two, and a parity check that reports that as model divergence is worse
/// than no check. Feed ``tensor(_:)`` for `"input"` straight into the provider.
///
/// Deliberately parsed by hand rather than through MLX. safetensors is a length,
/// a JSON header and a block of little-endian floats; a reader is forty lines.
/// Using MLX to load the *reference* would mean the thing under test and the
/// thing it is measured against share a code path, and a bug in that path would
/// cancel out instead of showing up.
public struct ParityArtifact: Sendable {

    /// Case name, e.g. `"frcrn_se_16k"`.
    public let name: String

    /// Native rate of this case. Nothing here is resampled.
    public let sampleRate: Int

    private let tensors: [String: [Float]]
    private let shapes: [String: [Int]]

    /// Flattened samples for one tensor, or nil if the artifact has no such name.
    public func tensor(_ name: String) -> [Float]? { tensors[name] }

    /// Dimensions of one tensor, as recorded.
    public func shape(_ name: String) -> [Int]? { shapes[name] }

    /// Every tensor name in the artifact, sorted.
    public var tensorNames: [String] { tensors.keys.sorted() }

    // MARK: - Loading

    public enum LoadError: Error, CustomStringConvertible {
        case truncated(String)
        case malformedHeader(String)
        case unsupportedDType(tensor: String, dtype: String)
        case incomplete(name: String, missing: String)

        public var description: String {
            switch self {
            case .truncated(let detail): "parity artifact is truncated: \(detail)"
            case .malformedHeader(let detail): "parity artifact header is malformed: \(detail)"
            case .unsupportedDType(let tensor, let dtype):
                "parity artifact tensor '\(tensor)' is \(dtype); only F32 is written by generate.py"
            case .incomplete(let name, let missing):
                """
                parity artifact '\(name)' is half present: \(missing) is missing. \
                Both files are written together, so this is an interrupted copy, \
                not an ungenerated case.
                """
            }
        }
    }

    private struct Sidecar: Decodable {
        let sampleRate: Int
        enum CodingKeys: String, CodingKey { case sampleRate = "sample_rate" }
    }

    private struct Entry: Decodable {
        let dtype: String
        let shape: [Int]
        let dataOffsets: [Int]
        enum CodingKeys: String, CodingKey {
            case dtype, shape
            case dataOffsets = "data_offsets"
        }
    }

    /// Load `<name>.safetensors` and its `<name>.json` sidecar from a directory.
    public init(name: String, in directory: URL) throws {
        let data = try Data(contentsOf: directory.appendingPathComponent("\(name).safetensors"))
        let sidecar = try JSONDecoder().decode(
            Sidecar.self,
            from: Data(contentsOf: directory.appendingPathComponent("\(name).json"))
        )

        guard data.count >= 8 else { throw LoadError.truncated("under 8 bytes") }
        let headerLength = data.prefix(8).withUnsafeBytes { Int(UInt64(littleEndian: $0.loadUnaligned(as: UInt64.self))) }
        let headerEnd = 8 + headerLength
        guard headerLength > 0, data.count >= headerEnd else {
            throw LoadError.truncated("header claims \(headerLength) bytes, file has \(data.count)")
        }

        let header = try JSONSerialization.jsonObject(with: data.subdata(in: 8..<headerEnd))
        guard let entries = header as? [String: Any] else {
            throw LoadError.malformedHeader("top level is not an object")
        }

        var tensors: [String: [Float]] = [:]
        var shapes: [String: [Int]] = [:]
        for (key, value) in entries where key != "__metadata__" {
            guard let raw = value as? [String: Any],
                  let entry = try? JSONDecoder().decode(
                      Entry.self, from: JSONSerialization.data(withJSONObject: raw)
                  ) else {
                throw LoadError.malformedHeader("entry '\(key)' is not a tensor descriptor")
            }
            guard entry.dtype == "F32" else {
                throw LoadError.unsupportedDType(tensor: key, dtype: entry.dtype)
            }
            guard entry.dataOffsets.count == 2 else {
                throw LoadError.malformedHeader("entry '\(key)' has malformed data_offsets")
            }
            // Everything below is checked rather than assumed. These bounds come
            // from a file, and an unchecked one traps in `subdata` or
            // `loadUnaligned` - a crash where a thrown LoadError is wanted.
            let lower = entry.dataOffsets[0]
            let upper = entry.dataOffsets[1]
            guard lower >= 0, upper >= lower else {
                throw LoadError.malformedHeader(
                    "entry '\(key)' has negative or inverted data_offsets \(entry.dataOffsets)"
                )
            }
            let (start, startOverflowed) = headerEnd.addingReportingOverflow(lower)
            let (end, endOverflowed) = headerEnd.addingReportingOverflow(upper)
            guard !startOverflowed, !endOverflowed, end <= data.count else {
                throw LoadError.truncated("tensor '\(key)' runs past the end of the file")
            }

            let byteCount = end - start
            guard byteCount.isMultiple(of: 4) else {
                throw LoadError.malformedHeader(
                    "entry '\(key)' spans \(byteCount) bytes, not a whole number of float32"
                )
            }

            guard entry.shape.allSatisfy({ $0 >= 0 }) else {
                throw LoadError.malformedHeader("entry '\(key)' has a negative dimension in \(entry.shape)")
            }
            var expected = 1
            for dimension in entry.shape {
                let (product, overflowed) = expected.multipliedReportingOverflow(by: dimension)
                guard !overflowed else {
                    throw LoadError.malformedHeader("entry '\(key)' has an unrepresentable shape \(entry.shape)")
                }
                expected = product
            }
            guard byteCount / 4 == expected else {
                throw LoadError.malformedHeader(
                    "entry '\(key)' declares shape \(entry.shape) (\(expected) floats) but spans \(byteCount / 4)"
                )
            }

            let bytes = data.subdata(in: start..<end)
            tensors[key] = bytes.withUnsafeBytes { buffer in
                stride(from: 0, to: buffer.count, by: 4).map {
                    Float(bitPattern: UInt32(littleEndian: buffer.loadUnaligned(fromByteOffset: $0, as: UInt32.self)))
                }
            }
            shapes[key] = entry.shape
        }

        self.name = name
        self.sampleRate = sidecar.sampleRate
        self.tensors = tensors
        self.shapes = shapes
    }
}

// MARK: - Metrics

/// How a candidate compares to a recorded reference.
///
/// SNR in dB is the metric the conversion work already used - `Models/python/
/// frcrn_se_mlx/README.md` records 115.98 dB for MLX against PyTorch - so numbers
/// here are directly comparable to the ones recorded then.
public enum ParityMetrics {

    /// Signal-to-noise ratio of `candidate` against `reference`, in dB.
    ///
    /// float32 round-off alone lands around 110-130 dB. Under roughly 60 dB is a
    /// real difference, not accumulated error. Returns `.infinity` when the two
    /// are bit-identical, and `-.infinity` when either side is not finite.
    ///
    /// The non-finite check is load-bearing, not defensive. A single NaN anywhere
    /// makes `noise` NaN, and `NaN > 0` is false - so the bit-identical branch
    /// would return `.infinity` and a model emitting NaN would clear every
    /// threshold in the suite. Infinity has to mean "no error", so it is reserved
    /// for `noise == 0` and nothing else.
    public static func snrDB(reference: [Float], candidate: [Float]) -> Double {
        precondition(reference.count == candidate.count, "compare equal lengths; see lengthReport")
        var signal = 0.0
        var noise = 0.0
        for index in reference.indices {
            let value = Double(reference[index])
            let error = value - Double(candidate[index])
            signal += value * value
            noise += error * error
        }
        guard signal.isFinite, noise.isFinite else { return -.infinity }
        guard noise > 0 else { return .infinity }
        guard signal > 0 else { return -.infinity }
        return 10 * log10(signal / noise)
    }

    /// Largest absolute sample difference. Useful when SNR is high but a single
    /// sample is wrong - a boundary, a first frame, an off-by-one.
    public static func maxAbsDiff(reference: [Float], candidate: [Float]) -> Double {
        precondition(reference.count == candidate.count, "compare equal lengths; see lengthReport")
        var worst = 0.0
        for index in reference.indices {
            worst = max(worst, abs(Double(reference[index]) - Double(candidate[index])))
        }
        return worst
    }

    /// Root mean square of a signal.
    public static func rms(_ samples: [Float]) -> Double {
        guard !samples.isEmpty else { return 0 }
        let total = samples.reduce(0.0) { $0 + Double($1) * Double($1) }
        return (total / Double(samples.count)).squareRoot()
    }

    /// Length is reported separately, never silently trimmed.
    ///
    /// Models here legitimately return fewer samples than they were given - FRCRN
    /// turns 99946 into 99840, which is STFT framing and matches the reference
    /// exactly. But a Swift wrapper that pads back to the input length is a real
    /// difference in the wrapper, and trimming to the shorter array before
    /// measuring would hide it. So callers assert the count first and only then
    /// compare.
    public static func lengthReport(reference: [Float], candidate: [Float]) -> String {
        "reference \(reference.count) samples, candidate \(candidate.count)"
    }
}

// MARK: - Gating

extension TestGate {

    /// Parity tests are opted into separately from other integration tests.
    ///
    /// They need both the weights *and* the generated artifacts, and the artifacts
    /// are published alongside the weights rather than committed - see
    /// `Parity/README.md`. `swift test` stays hermetic either way.
    public static var runParityTests: Bool {
        ProcessInfo.processInfo.environment["RUN_PARITY_TESTS"] == "1"
    }

    /// Record mode: report the measured numbers instead of asserting them.
    ///
    /// The first run against a new case has nothing to assert against, and a
    /// threshold invented before measuring is not a threshold. Run with
    /// `PARITY_RECORD=1`, read the numbers, write them into `ParityThresholds`.
    public static var recordParityBaselines: Bool {
        ProcessInfo.processInfo.environment["PARITY_RECORD"] == "1"
    }

    public static let parityDisabled =
        "parity test - set RUN_PARITY_TESTS=1 to run (needs model weights and Parity/artifacts)"

    /// Where the generated artifacts live.
    ///
    /// `Parity/artifacts/` under the package by default; override with
    /// `AUDIOTOOL_PARITY_DIR` to point at a download of the published set.
    public static let parityArtifactDirectory: URL? = {
        if let override = ProcessInfo.processInfo.environment["AUDIOTOOL_PARITY_DIR"] {
            return URL(fileURLWithPath: override)
        }
        // ParityArtifact.swift -> TestSupport -> Tests -> AudioToolSwift
        var url = URL(fileURLWithPath: #filePath)
        for _ in 0..<3 { url.deleteLastPathComponent() }
        return url.appendingPathComponent("Parity/artifacts")
    }()

    /// Load a parity case, or nil if it has not been generated on this machine.
    ///
    /// Absent and malformed are deliberately not the same outcome. Absent means
    /// "not generated here" and is a legitimate skip. A file that is present but
    /// truncated, or carries an unreadable sidecar or an unsupported dtype, is a
    /// broken published artifact - swallowing that into the same `nil` would let
    /// the suite report a skip and stay green over a real defect, so it throws.
    /// Both files are written in one step by `generate.py`, so exactly one of them
    /// existing is an interrupted copy rather than an ungenerated case, and gets
    /// the same treatment as a corrupt one.
    public static func parityArtifact(_ name: String) throws -> ParityArtifact? {
        guard let directory = parityArtifactDirectory else { return nil }
        let manager = FileManager.default
        let tensors = directory.appendingPathComponent("\(name).safetensors")
        let sidecar = directory.appendingPathComponent("\(name).json")
        let hasTensors = manager.fileExists(atPath: tensors.path)
        let hasSidecar = manager.fileExists(atPath: sidecar.path)

        guard hasTensors || hasSidecar else { return nil }
        guard hasTensors, hasSidecar else {
            throw ParityArtifact.LoadError.incomplete(
                name: name,
                missing: (hasTensors ? sidecar : tensors).lastPathComponent
            )
        }
        return try ParityArtifact(name: name, in: directory)
    }

    /// Weights staged where a test runner can read them.
    ///
    /// The Swift Hub library caches under `~/Documents/huggingface/models`, which
    /// macOS protects with TCC, and the xcodebuild test runner has not been
    /// granted access to it - it gets `NSCocoaErrorDomain 257`. So parity tests
    /// never resolve weights through the cache; they take an explicit path under
    /// `Parity/weights`, populated by `Scripts/stage-parity-weights.sh`.
    ///
    /// Override with `AUDIOTOOL_PARITY_WEIGHTS`.
    public static let parityWeightsDirectory: URL? = {
        if let override = ProcessInfo.processInfo.environment["AUDIOTOOL_PARITY_WEIGHTS"] {
            return URL(fileURLWithPath: override)
        }
        // ParityArtifact.swift -> TestSupport -> Tests -> AudioToolSwift
        var url = URL(fileURLWithPath: #filePath)
        for _ in 0..<3 { url.deleteLastPathComponent() }
        return url.appendingPathComponent("Parity/weights")
    }()

    /// A staged file, e.g. `parityWeights("MossFormer2_SE_48K_MLX", "model_fp32.safetensors")`.
    public static func parityWeights(_ repo: String, _ file: String) -> URL? {
        guard let directory = parityWeightsDirectory else { return nil }
        let candidate = directory.appendingPathComponent(repo).appendingPathComponent(file)
        guard FileManager.default.fileExists(atPath: candidate.path) else { return nil }
        return candidate
    }

    /// Message for `XCTSkip` when ``parityWeights(_:_:)`` returns nil.
    public static func missingParityWeights(_ repo: String, _ file: String) -> String {
        "\(repo)/\(file) is not staged - run Scripts/stage-parity-weights.sh"
    }

    /// Message for `XCTSkip` when ``parityArtifact(_:)`` returns nil.
    public static func missingParityArtifact(_ name: String) -> String {
        """
        parity artifact '\(name)' not found in \(parityArtifactDirectory?.path ?? "<unset>"). \
        Generate it with Parity/generate.py, or point AUDIOTOOL_PARITY_DIR at a download \
        of the published set.
        """
    }
}
