#!/usr/bin/env bash
#
# Fetch and derive the downloadable test audio fixtures.
#
# NOT everything in Tests/**/Fixtures comes from here. Six files - test.wav,
# test_48k.wav, sr_input_16k.wav, speech_dialogue.wav, mix_8k.wav and mix3_8k.wav -
# are the inputs each model's conversion was validated against, carried over from the
# conversion working trees and committed directly. They cannot be regenerated by this
# script, and should not be overwritten by it: tests run against them are directly
# comparable to the checks done during conversion.
#
# Everything here is openly licensed and small. The upstream speech samples come
# from ClearerVoice-Studio, which is Apache-2.0 - the same licence as this project -
# and which is where MossFormer2 SE/SS/SR and FRCRN originate, so these are the
# clips those models are demoed on. Music is CC0.
#
# The committed fixtures were produced by this script; it exists so their
# provenance is reproducible rather than asserted.
#
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

CVS="https://raw.githubusercontent.com/modelscope/ClearerVoice-Studio/main"
FA="Tests/AudioToolFluidAudioTests/Fixtures"
US="Tests/AudioToolUSSTests/Fixtures"
TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT
mkdir -p "$FA" "$US"

command -v ffmpeg >/dev/null || { echo "error: ffmpeg required (brew install ffmpeg)" >&2; exit 1; }

echo "Fetching ClearerVoice-Studio samples (Apache-2.0)..."
curl -sfL "$CVS/clearvoice/samples/path_to_input_wavs_sr/LJ001-0001.wav" -o "$TMP/ljspeech.wav"
curl -sfL "$CVS/clearvoice/samples/path_to_input_wavs_ss/speech_mixure1.wav" -o "$TMP/multi.wav"

echo "Fetching CC0 music (archive.org, CC0 1.0)..."
curl -sfL "https://archive.org/download/MarchForHonor/Distant_Wonders.mp3" -o "$TMP/music.mp3"

echo "Deriving fixtures..."
cp "$TMP/ljspeech.wav" "$FA/speech_long.wav"
cp "$TMP/multi.wav"    "$FA/multi_speaker.wav"
# test.wav must be speech at 16 kHz: it backs the VAD, transcription and
# diarization tests. ClearerVoice's own test.wav is 48 kHz and not speech-dominant,
# so this concatenates three of their speech samples instead.

ff() { ffmpeg -hide_banner -loglevel error -y "$@"; }
ff -i "$TMP/music.mp3" -ss 20 -t 10 -ar 44100 -ac 2 -c:a pcm_s16le "$FA/music.wav"

echo "Done:"; du -sh "$FA" "$US"
